server:
  port: 7018
spring:
  application:
    name: zagy-sptsjzx-qtxljcgkpt
  config:
    import:
      - optional:nacos:jeecg.yaml
      - optional:nacos:jeecg-@profile.name@.yaml
  cloud:
    nacos:
      config:
        server-addr: @config.server-addr@
        group: @config.group@
        namespace: @config.namespace@
        username: @config.username@
        password: @config.password@
      discovery:
        server-addr: ${spring.cloud.nacos.config.server-addr}
        namespace: @config.namespace@
        username: @config.username@
        password: @config.password@
        group: @config.group@