jeecg:
  route:
    config:
      #type:database nacos yml
      data-type: database
      data-id: jeecg-gateway-router
spring:
  redis:
    database: 0
    host: 192.168.1.3
    port: 6379
    password: zlkj123456
knife4j:
  production: false